-- BEAM for Individuals - Business Type Taxonomy Data
-- Insert 50+ business types with keywords and typical competitors

INSERT INTO business_types (id, type_name, category, description, keywords, typical_competitors) VALUES
('bt-001', 'Hair Salon', 'Personal Care', 'Professional hair styling and salon services', JSON_ARRAY('hair salon', 'haircut', 'hair color', 'styling'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-002', 'Nail Salon', 'Personal Care', 'Manicure and pedicure services', JSON_ARRAY('nail salon', 'manicure', 'pedicure', 'nail art'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-003', 'Spa', 'Personal Care', 'Massage and wellness services', JSON_ARRAY('spa', 'massage', 'wellness', 'relaxation'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-004', 'Gym', 'Fitness', 'Fitness center and gym services', JSON_ARRAY('gym', 'fitness', 'workout', 'training'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-005', 'Yoga Studio', 'Fitness', 'Yoga classes and instruction', JSON_ARRAY('yoga', 'yoga classes', 'meditation', 'wellness'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-006', 'Personal Training', 'Fitness', 'Personal fitness training services', JSON_ARRAY('personal trainer', 'fitness training', 'coaching'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-007', 'Dental Clinic', 'Health', 'Dental care and treatment services', JSON_ARRAY('dentist', 'dental care', 'teeth cleaning'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-008', 'Medical Clinic', 'Health', 'General medical practice', JSON_ARRAY('doctor', 'medical clinic', 'healthcare'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-009', 'Veterinary Clinic', 'Health', 'Pet medical services', JSON_ARRAY('veterinarian', 'vet', 'pet care'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-010', 'House Cleaning', 'Home Services', 'Residential cleaning services', JSON_ARRAY('house cleaning', 'maid service', 'cleaning'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-011', 'Plumbing', 'Home Services', 'Plumbing repair and installation', JSON_ARRAY('plumber', 'plumbing repair', 'pipe repair'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-012', 'Electrical', 'Home Services', 'Electrical repair and installation', JSON_ARRAY('electrician', 'electrical repair', 'wiring'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-013', 'Landscaping', 'Home Services', 'Lawn and garden services', JSON_ARRAY('landscaping', 'lawn care', 'gardening'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-014', 'Restaurant', 'Food & Beverage', 'Full-service restaurant', JSON_ARRAY('restaurant', 'dining', 'food'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-015', 'Cafe', 'Food & Beverage', 'Coffee shop and cafe', JSON_ARRAY('cafe', 'coffee shop', 'bakery'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-016', 'Bakery', 'Food & Beverage', 'Bakery and pastry shop', JSON_ARRAY('bakery', 'pastry', 'bread'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-017', 'Pizzeria', 'Food & Beverage', 'Pizza restaurant', JSON_ARRAY('pizza', 'pizzeria', 'italian food'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-018', 'Clothing Store', 'Retail', 'Apparel and fashion retail', JSON_ARRAY('clothing store', 'fashion', 'apparel'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-019', 'Bookstore', 'Retail', 'Book retail store', JSON_ARRAY('bookstore', 'books', 'reading'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-020', 'Electronics Store', 'Retail', 'Electronics and gadgets retail', JSON_ARRAY('electronics', 'gadgets', 'tech store'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-021', 'Furniture Store', 'Retail', 'Furniture and home decor retail', JSON_ARRAY('furniture', 'home decor', 'interior'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-022', 'Accounting', 'Professional Services', 'Accounting and bookkeeping services', JSON_ARRAY('accountant', 'accounting', 'bookkeeping'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-023', 'Law Firm', 'Professional Services', 'Legal services and consultation', JSON_ARRAY('lawyer', 'legal services', 'attorney'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-024', 'Consulting', 'Professional Services', 'Business consulting services', JSON_ARRAY('consultant', 'consulting', 'business advice'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-025', 'Marketing Agency', 'Professional Services', 'Marketing and advertising services', JSON_ARRAY('marketing', 'advertising', 'seo'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-026', 'Photography', 'Professional Services', 'Photography services', JSON_ARRAY('photographer', 'photography', 'portraits'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-027', 'Tutoring', 'Education', 'Educational tutoring services', JSON_ARRAY('tutor', 'tutoring', 'education'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-028', 'Language School', 'Education', 'Language learning classes', JSON_ARRAY('language school', 'english classes', 'language learning'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-029', 'Music School', 'Education', 'Music lessons and instruction', JSON_ARRAY('music school', 'music lessons', 'piano lessons'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-030', 'Art School', 'Education', 'Art classes and instruction', JSON_ARRAY('art school', 'art classes', 'painting'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-031', 'Auto Repair', 'Automotive', 'Car repair and maintenance', JSON_ARRAY('auto repair', 'car repair', 'mechanic'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-032', 'Car Wash', 'Automotive', 'Car washing and detailing', JSON_ARRAY('car wash', 'auto detailing', 'car cleaning'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-033', 'Gas Station', 'Automotive', 'Fuel and convenience services', JSON_ARRAY('gas station', 'fuel', 'convenience store'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-034', 'Movie Theater', 'Entertainment', 'Movie cinema and entertainment', JSON_ARRAY('movie theater', 'cinema', 'movies'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-035', 'Bowling Alley', 'Entertainment', 'Bowling and recreation', JSON_ARRAY('bowling', 'bowling alley', 'recreation'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-036', 'Karaoke Bar', 'Entertainment', 'Karaoke and bar services', JSON_ARRAY('karaoke', 'karaoke bar', 'singing'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-037', 'Hotel', 'Hospitality', 'Hotel and lodging services', JSON_ARRAY('hotel', 'lodging', 'accommodation'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-038', 'Bed & Breakfast', 'Hospitality', 'Bed and breakfast accommodation', JSON_ARRAY('bed and breakfast', 'bnb', 'accommodation'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-039', 'Tour Company', 'Hospitality', 'Travel and tour services', JSON_ARRAY('tour', 'travel', 'vacation'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-040', 'Wedding Planner', 'Special Services', 'Wedding planning and coordination', JSON_ARRAY('wedding planner', 'event planning', 'wedding'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-041', 'Event Planner', 'Special Services', 'Event planning services', JSON_ARRAY('event planner', 'event planning', 'events'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-042', 'Florist', 'Special Services', 'Flower and floral arrangement services', JSON_ARRAY('florist', 'flowers', 'floral arrangements'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-043', 'Pet Grooming', 'Special Services', 'Pet grooming and care', JSON_ARRAY('pet grooming', 'dog grooming', 'pet care'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-044', 'Tailor', 'Special Services', 'Clothing alteration and tailoring', JSON_ARRAY('tailor', 'alterations', 'clothing repair'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-045', 'Locksmith', 'Special Services', 'Locksmith services', JSON_ARRAY('locksmith', 'lock repair', 'key services'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-046', 'Real Estate', 'Professional Services', 'Real estate sales and services', JSON_ARRAY('real estate', 'realtor', 'property'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-047', 'Insurance', 'Professional Services', 'Insurance services', JSON_ARRAY('insurance', 'insurance agent', 'coverage'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-048', 'Bank', 'Professional Services', 'Banking services', JSON_ARRAY('bank', 'banking', 'financial services'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-049', 'Car Rental', 'Automotive', 'Vehicle rental services', JSON_ARRAY('car rental', 'vehicle rental', 'rent a car'), JSON_ARRAY('Competitor A', 'Competitor B')),
('bt-050', 'Laundry', 'Home Services', 'Laundry and dry cleaning', JSON_ARRAY('laundry', 'dry cleaning', 'laundromat'), JSON_ARRAY('Competitor A', 'Competitor B'));

-- Record migration
INSERT INTO migrations (name) VALUES ('002_insert_taxonomy_data') ON DUPLICATE KEY UPDATE executed_at = CURRENT_TIMESTAMP;
